language: bash
sudo: required

before_install:
  - docker pull weecology/portal_predictions:2019-03-21
  - docker run --name ppred -t -d weecology/portal_predictions:2019-03-21 /bin/bash
  - docker cp ../portalPredictions ppred:/
  - docker exec -i ppred ls portalPredictions

script:
  - docker exec --env GITHUB_PAT=$GITHUB_PAT -i ppred bash -c "cd portalPredictions && Rscript PortalForecasts_travis.R"
  - docker exec --env GITHUB_PAT=$GITHUB_PAT -i ppred bash -c "cd portalPredictions && Rscript tests/testthat.R"

after_success:
  - docker cp ppred:/portalPredictions portalPredictionsResult
  - cd portalPredictionsResult
  - bash archive.sh